PA-4-create-workflow
LCJG-BetaLabs/ds-club-monaco-persona pull request #3
Opened 2024-03-12 09:51 UTC by seanchan-lcjg

Create workflow for Club Monaco Persona:
1. Create datamart
2. generate tagging parquet
3. generate model feature
4. predict data by previous kmeans model
5. create profiling of the customer segment (SOW, no. of customer)
6. export csv (no. of customer in each cluster)
7. send email (SOW of main class, sub class, no. of customer)

2024-03-13 06:18 UTC, cintiaching requested changes

2024-03-13 06:18 UTC, cintiaching commented on workflow/workflow.py
restructure the files as discussed, `workflow` folder seems unnecessary

2024-03-13 06:18 UTC, cintiaching commented on workflow/profiling/profile_and_export.py
> +
nice

2024-03-13 06:18 UTC, cintiaching commented on workflow/profiling/profile_and_export.py
> +
as per Arnab's comments, the schema should be
```
vip_no
persona
date
```
and whatever he selected from olga's list

2024-03-13 06:18 UTC, cintiaching commented on workflow/profiling/profile_and_export.py
> +send_email(
rmb to change the email title as arnab mentioned, and add the csv as attachment

2024-03-14 07:13 UTC, cintiaching approved these changes
lgtm, thanksss

2024-03-14 07:13 UTC, cintiaching commented on model_features.py
> +datamart_dir = dbutils.widgets.get("base_dir") + "/datamart"
`datamart_dir = os.path.join(dbutils.widgets.get("base_dir"), "datamart")`

2024-03-14 08:34 UTC, seanchan-lcjg commented on workflow/model_features.py
changed

2024-03-14 08:35 UTC, merged